# Label rules for https://github.com/actions/labeler

# Labels from branch names
'fix':
  - head-branch: ['fix']

'enhancement':
  - head-branch: ['feat']

# Documentation labels
'docs':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/**/*.rst']
          - all-globs-to-all-files: ['!doc/source/examples.rst', '!doc/source/api/**/*.rst',
              '!doc/styles/**', '!doc/.vale.ini']

'docs:api':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['doc/source/api/**/*.rst']

'docs:examples':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['examples/**/*.py', 'doc/source/examples.rst']

# Other labels
'style:code':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.pre-commit-config.yaml', 'doc/.vale.ini']

'docker':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['docker/**']

'ci':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['.github/workflows/**']

'tests':
  - any:
      - changed-files:
          - any-glob-to-any-file: ['tests/**']

# Keep these labels when the labeler updates a pull request.
# See https://github.com/actions/labeler/issues/763.

'ci:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'docs:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'tests:skip':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']

'blocked':
  - all:
      - changed-files:
          - all-globs-to-all-files: ['THIS-NEVER-MATCHES-A-FILE']
