repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.6
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: ["--ignore-words-list", "afterall,synopsys"]

- repo: https://github.com/pycontribs/mirrors-prettier
  rev: v3.4.2
  hooks:
  - id: prettier
    types_or: [css, javascript]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

# Validate GitHub workflows and local actions.
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.0
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
