ci:
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    For more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: 'chore/pre-commit-autoupdate'
  autoupdate_commit_msg: 'chore: pre-commit automatic update'
  autoupdate_schedule: weekly

repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 3b4bc031619cde2e0a9f3c4441ac7cc8227245a4 # v0.14.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 1e30511413f07e516c1844ba91abce8aca984963 # 1.18.0
    hooks:
      - id: zizmor
        args: ["--pedantic"]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: fda77690955e9b63c6687d8806bafd56a526e45f # 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==25.1.0]
        args: ["--line-length=88"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # v2.4.1
    hooks:
      - id: codespell
        exclude: ^(tests/|doc/_build/|doc/styles/|doc/source/_static/)
        args: ["--ignore-words-list", "afterall,synopsys"]

  - repo: https://github.com/google/yamlfmt
    rev: 42486acb2b9ef7aa4850b754d933989bca887349 # v0.20.0
    hooks:
      - id: yamlfmt
        args:
          - "-formatter"
          - "max_line_length=80,retain_line_breaks=true,retain_line_breaks_single=true"

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 69b77b8d2436cb00c886f129dda7f68f3b2909ac # v2.11.0
    hooks:
      - id: pyproject-fmt
        args: [--keep-full-version]

  - repo: https://github.com/pycontribs/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        types_or: [css, javascript]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
