[tox]
description = Default tox environments list
envlist =
    code-style
    doc-style-{linux,windows}
    doc-{links,html}
    tests
    tests-python
skip_missing_interpreters = true
isolated_build = true
isolated_build_env = build

[testenv]
description = Test the project
basepython =
    {code-style,doc,doc-style}: python3
setenv =
    PYTHONUNBUFFERED = yes

[testenv:code-style]
description = Checks project code style
skip_install = true
deps =
    pre-commit
commands =
    pre-commit install
    pre-commit run --all-files --show-diff-on-failure

[testenv:doc-style-{linux,windows}]
description = Checks project documentation style
skip_install = true
deps = docutils==0.22.4
allowlist_externals =
    find
    vale
    bash
    cmd
platform =
    linux: linux
    windows: win32
commands =
    linux: bash -c 'rst_files=$(find {toxinidir}/doc/source -type f -name "*.rst") && vale sync --config="{toxinidir}/doc/.vale.ini" && vale --config="{toxinidir}/doc/.vale.ini" $rst_files'
    windows: cmd /c "dir /s /b {toxinidir}\doc\source\*.rst > tmp_files.txt"
    windows: cmd /c "vale sync --config="{toxinidir}\doc\.vale.ini""
    windows: cmd /v:on /c "set vale_files="" && (for /f %i in (tmp_files.txt) do @set vale_files="%i" !vale_files!) && @del tmp_files.txt && vale --config="{toxinidir}\doc\.vale.ini" !vale_files!"

[testenv:doc-{links,html}]
description =
    links: Check documentation links
    html: Build HTML documentation
allowlist_externals =
    pdflatex
setenv =
    SOURCE_DIR = doc/source
    BUILD_DIR = doc/_build
    links: BUILDER = linkcheck
    html: BUILDER = html
    links,html,pdf: BUILDER_OPTS = --color -v -j auto -W --keep-going
passenv =
    DOCUMENTATION_CNAME
    DOCUMENTATION_BASE_URL
dependency_groups =
    links,html,pdf: doc
commands =
    sphinx-build -d "{toxworkdir}/doc_doctree" {env:SOURCE_DIR} "{toxinidir}/{env:BUILD_DIR}/{env:BUILDER}" {env:BUILDER_OPTS} -b {env:BUILDER}

[testenv:tests]
description = Run project tests
skip_install = true
allowlist_externals =
    npm
commands =
    npm ci
    npm test

[testenv:tests-python]
description = Check generated theme navigation and assets
commands = python -m unittest discover -s tests/python
