[theme]
inherit = basic
stylesheet = css/style.css
pygments_style = friendly

[options]
site_description =
footer_text =
github_url =
linkedin_url =
youtube_url =
rss_url =
sponsor_url =
versions_url =
