StylesPath = styles
MinAlertLevel = warning
Packages = Google
Vocab = Theme

IgnoredScopes = code, tt
SkippedScopes = script, style, pre, figure
WordTemplate = \b(?:%s)\b

[*.{md,rst}]
BasedOnStyles = Vale, Google
# Project documentation uses Title Case headings.
Google.Headings = NO
Vale.Terms = NO
TokenIgnores = (\$+[^\n$]+\$+), (:.*:`.*`)|(<.*>)
BlockIgnores = (?m)^\.\. math::(?:\n(?:[ \t]+[^\n]*|[ \t]*))*
